Update documentation action (#40)
* Update documentation action

* improve doc

* conf

* remove fLOG

* remove MlGridBenchmark

* ut

* remove @file

* doc

* fix many warnings

* improve documentation

* new series of improvments

* improvment

* tabs

* conf

* fix warnings

* nit

diff --git a/.github/workflows/documentation.yml b/.github/workflows/documentation.yml
--- a/.github/workflows/documentation.yml
+++ b/.github/workflows/documentation.yml
@@ -33,6 +33,8 @@ jobs:
         with:
           python-version: '3.11'
 
+      - uses: tlylt/install-graphviz@v1
+
       - name: Install pandoc
         run: sudo apt-get install -y pandoc
 
@@ -47,13 +49,27 @@ jobs:
 
       - name: Copy license
         run: cp LICENSE* ./_doc
-      - name: Copy readme
-        run: cp README* ./_doc
       - name: Copy changelogs
         run: cp CHANGELOGS* ./_doc
 
       - name: Documentation
-        run: python -m sphinx ./_doc ./dist/html
+        run: python -m sphinx ./_doc ./dist/html -n -w doc.txt
+
+      - name: Summary
+        run: cat doc.txt
+
+      - name: Check for errors and warnings
+        run: |
+          if [[ $(grep ERROR doc.txt) ]]; then
+            echo "Documentation produces errors."
+            grep ERROR doc.txt
+            exit 1
+          fi
+          if [[ $(grep WARNING doc.txt) ]]; then
+            echo "Documentation produces warnings."
+            grep WARNING doc.txt
+            exit 1
+          fi
 
       - uses: actions/upload-artifact@v3
         with:
